base/urls.py
from django.contrib import admin
from django.urls import path, include
from turbo_parser.views import index, instructions

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('instructions/', instructions, name='instructions'),
    path('users/', include('users.urls')),
    path('turbo_parser/', include('turbo_parser.urls')),
]

turbo_parser/urls.py
from django.urls import path
from . import views

app_name = 'turbo_parser'

urlpatterns = [
    path('orders/', views.orders, name='orders'),
    path('orders/id=<int:id>/', views.order_details, name='order_details'),
    path('orders/add_order/', views.add_order, name='add_order'),
    path('orders/delete=<int:order_id>/', views.delete_order, name='delete_order'),
    path('orders/edit=<int:order_id>/', views.edit_order, name='edit_order'),
    path('profile/', views.profile, name='profile'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

turbo_parser/models.py
from django.db import models
from django.utils import timezone
from users.models import User

# Create your models here.

class Order(models.Model):
    threshold = models.FloatField()
    currency = models.CharField(max_length=3)
    created_at = models.DateTimeField(default=timezone.now)
    ordered_link = models.URLField(max_length=3000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return 'Order Object (id=' + str(self.id) + ')'


class SendedLink(models.Model):
    sended_link = models.CharField(max_length=300)
    sended_at = models.DateTimeField(default=timezone.now)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return 'SendedLink Object (id=' + str(self.id)+')'

turbo_parser/forms.py
from django import forms
from turbo_parser.models import Order

CHOICES= (
('USD','USD'),
('AZN','AZN'),
('EUR','EUR'),
)

class AddOrderForm(forms.ModelForm):
    threshold = forms.FloatField(widget=forms.NumberInput())
    currency = forms.CharField(widget=forms.Select(choices=CHOICES))
    ordered_link = forms.URLField(widget=forms.TextInput(attrs={'placeholder': '...'}))

    class Meta:
        model = Order
        fields = ('threshold', 'currency', 'ordered_link')

    def __init__(self,  *args, **kwargs):
        super(AddOrderForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['currency'].widget.attrs['class'] = 'form-select'

turbo_parser/views.py
from django.shortcuts import render, get_object_or_404
from .models import Order, SendedLink
from users.models import User
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from turbo_parser.forms import AddOrderForm
from users.forms import UserProfileForm

def index(request):
    return render(request, 'turbo_parser/index.html')

def instructions(request):
    return render(request, 'turbo_parser/instructions.html')


def orders(request):
    orders = Order.objects.filter(user=request.user)
    my_list = []

    max_num_of_orders = User.objects.get(id=request.user.id).max_num_of_orders
    num_of_orders = len(Order.objects.filter(user_id=request.user.id))
    num_orders_left = max_num_of_orders - num_of_orders

    for i in orders:
        num_sended_links_for_i = len(i.sendedlink_set.all())
        my_list.append((i, num_sended_links_for_i))
    
    context = {
        'my_list': my_list,
        'user': request.user,
        'max_num_of_orders': max_num_of_orders,
        'num_of_orders': num_of_orders,
        'num_orders_left':num_orders_left,
    }

    return render(request, 'turbo_parser/orders.html', context)


def order_details(request, id):

    # Option 1
    # try:
    #     order = Order.objects.get(pk=id)
    #     data = [order]

    #     sended_links_for_order = order.sendedlink_set.all()
    #     data.append(sended_links_for_order)

    #     return render(request, 'order_details.html',{'data':data})
    # except Order.DoesNotExist:
    #     raise Http404() 

    # Option 2
    order = get_object_or_404(Order, pk=id)
    data = [order]

    sended_links_for_order = order.sendedlink_set.all()
    data.append(sended_links_for_order)
    
    return render(request, 'turbo_parser/order_details.html',{'data':data})

        

def add_order(request):
    if request.method == "POST":
        form = AddOrderForm(data=request.POST)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.user = request.user
            new_order.save()
            return HttpResponseRedirect(reverse('turbo_parser:orders'))
        else:
            print('not valid')
    else:
        form = AddOrderForm()
        max_num_of_orders = User.objects.get(id=request.user.id).max_num_of_orders
        num_of_orders = len(Order.objects.filter(user_id=request.user.id))
        num_orders_left = max_num_of_orders - num_of_orders
        if num_of_orders >= max_num_of_orders:
            return HttpResponseRedirect(reverse('turbo_parser:orders'))

    context = {'form': form}
    return render(request, 'turbo_parser/add_order.html', context)


def delete_order(request, order_id):
    order_to_delete = Order.objects.get(pk=order_id)
    order_to_delete.delete()
    return HttpResponseRedirect(reverse('turbo_parser:orders'))

def edit_order(request, order_id):
    order_object = Order.objects.get(pk=order_id)

    if request.method == 'POST':
        form = AddOrderForm(data=request.POST, instance=order_object)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('turbo_parser:orders'))
        else:
            print('not valid')

    else:
        form = AddOrderForm(instance=order_object)

    context = {'form': form}
    return render(request, 'turbo_parser/edit_order.html', context)


def profile(request):

    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('turbo_parser:profile'))
        else:
            print('not valid')
        
    else:
        form = UserProfileForm(instance=request.user)

    user_orders=Order.objects.filter(user=request.user)
    context = {
        'form': form,
        'user_orders': len(user_orders),
    }
    return render(request, 'turbo_parser/profile.html', context)

turbo_parser/templates/turbo_parser/add_order.html
{% extends 'turbo_parser/base.html' %}

{% block title %}My cabinet | Adding new order{% endblock title %}

{% block moy_kontent %}
    
  <div class="container" style="margin-top: 100px;">



      <div class="row g-5">

        <div class="col-md-7 col-lg-8">
          <h4 class="mb-3">Add New Order</h4>
          <form class="needs-validation" action={% url 'turbo_parser:add_order' %} method="post">
            {% csrf_token %}
            <div class="row g-3">
            

              <div class="col-12">
                <label for={{ form.ordered_link.id_for_label }} class="form-label">Insert here link of search result:</label>
                <div class="input-group has-validation">
                  <span class="input-group-text mr-2">Link:</span>
                  {{ form.ordered_link }}
                
                </div>
              </div>
              <div class="d-flex align-items-center">
                <div class="col-md-3" style="">
                  <label for={{ form.currency.id_for_label }} class="form-label">Currency</label>
                  {{ form.currency }}
  
                </div> 
                <div class="col-md-6">
                  <label for={{ form.threshold.id_for_label }} class="form-label">Price Threshold</label>
                  {{ form.threshold }}
  
                </div>

              </div>

            </div>

            <button class="w-20 btn btn-primary btn-lg" style="margin-top: 30px;" type="submit">Add Order</button>
          </form>
        </div>
      </div>
    

    
  </div>


{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block custom_css %}
    
    {% endblock custom_css %}
   
</head>
<body class="d-flex position-absolute w-100" style="min-height: 100vh;" >
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a href={% url 'index' %}><span class="navbar-brand">Turbo Parser</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href={% url 'turbo_parser:orders' %}>Orders <i class="fas fa-car"></i> </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={% url 'turbo_parser:profile' %}>{{ user.username }}
                                <i class="fas fa-user-circle"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href={% url 'users:logout' %}>Logout <i class="fas fa-sign-out-alt"></i></a>
                        </li>
                    {% else %}  
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Login <i class="fas fa-sign-in-alt"></i></a>
                        </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </nav>

    
    {% block moy_kontent %}
    
    {% endblock moy_kontent %}

    <!-- Bootstrap core JavaScript -->
    <script src={% static 'vendor/jquery/jquery.min.js' %}></script>
    <script src={% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}></script>

    <!-- FontAwesome script -->
    <script src={% static 'vendor/fontawesome/fontawesome-icons.js' %} crossorigin="anonymous"></script>
    
</body>
</html>

turbo_parser/templates/turbo_parser/edit_order.html
{% extends 'turbo_parser/base.html' %}

{% block title %}My cabinet | Adding new order{% endblock title %}

{% block moy_kontent %}
    
  <div class="container" style="margin-top: 100px;">



      <div class="row g-5">

        <div class="col-md-7 col-lg-8">
          <h4 class="mb-3">Edit Order</h4>
          <form class="needs-validation" action={% url 'turbo_parser:edit_order' form.instance.id %} method="post">
            {% csrf_token %}
            <div class="row g-3">
            

              <div class="col-12">
                <label for={{ form.ordered_link.id_for_label }} class="form-label">Insert here link of search result:</label>
                <div class="input-group has-validation">
                  <span class="input-group-text mr-2">Link:</span>
                  {{ form.ordered_link }}
                
                </div>
              </div>
              <div class="d-flex align-items-center">
                <div class="col-md-3" style="">
                  <label for={{ form.currency.id_for_label }} class="form-label">Currency</label>
                  {{ form.currency }}
  
                </div> 
                <div class="col-md-6">
                  <label for={{ form.threshold.id_for_label }} class="form-label">Price Threshold</label>
                  {{ form.threshold }}
  
                </div>

              </div>

            </div>

            <button class="w-20 btn btn-primary btn-lg" style="margin-top: 30px;" type="submit">Save</button>
          </form>
        </div>
      </div>
    

    
  </div>


{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/index.html
{% extends 'turbo_parser/base.html' %}

{% load static %}

{% block title %}Turbo Parser{% endblock title %}

{% block custom_css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block moy_kontent %}
    <!-- Page Content -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">Turbo Parser</h1>
                    <p>
                        Turbo Parser will immediately notify you about new opportunities.
                        Be our client and get bot who will browse market instead of you!
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href={% url 'instructions' %}>
                            Show Instuctions
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/instructions.html
{% extends 'turbo_parser/base.html' %}

{% load static %}

{% block title %}Turbo Parser{% endblock title %}

{% block custom_css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block moy_kontent %}

    <div class="container" style="margin-top: 70px; margin-left: 70px;">
        <video src="{% static 'vendor/video/trailer.mp4' %}" width="480" height="360" controls>  
            Your browser doesnt support the video tag                 
        </video>
    </div>
    
{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/order_details.html
{% extends 'turbo_parser/base.html' %}

{% block title %}My cabinet | Order details{% endblock title %}

{% block moy_kontent %}

  <div class="container" style="margin-top:120px;">
    <h2 style="margin-top: 100px;">Order id: {{ data.0.id }}</h2>
    <div class="table-responsive">
      <table class="table table-striped table-sm table-hover">
        <thead>
          <tr>
            <th scope="col">Sended Link id</th>
            <th scope="col">Sended at</th>
            <th scope="col">Sended Link</th>
            <th scope="col">Ordered link</th>
          </tr>
        </thead>
        <tbody>
          {% for link in data.1 %}
          <tr>
            <td>{{ link.id }}</td>
            <td>{{ link.sended_at }}</td>
            <td><a href=//{{ link.sended_link }} target="_blank">{{ link.sended_link }}</a></td>
            <td><a href=//{{ data.0.ordered_link }} target="_blank">{{ data.0.ordered_link }}</a></td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
    </div>
  </div>
  


{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/orders.html
{% extends 'turbo_parser/base.html' %}
{% load static %}
{% block title %}My orders{% endblock title %}

{% block custom_css %}
  <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block moy_kontent %}

<div class="container-fluid d-block w-100" style="margin-top:20px; width:100%;">
  
  <section class="col-lg-3 container ml-0" style="position: relative;">
    <li class="text-primary d-flex justify-content-between m-2">
     <span class="d-flex align-items-center">Allowed Number Of Orders:</span>
     <h4 class="mt-2 mr-5">
      <span class="badge bg-primary rounded-pill text-white lg">
        {{ max_num_of_orders }}
      </span>
      </h4>
    </li>
    <li class="text-primary d-flex justify-content-between m-2">
     <span class="d-flex align-items-center">Number of Active Orders:</span>
     <h4 class="mt-2 mr-5">
      <span class="badge bg-success rounded-pill text-white">
        {{ num_of_orders }}
      </span>
    </h4>
    </li>
    <li class="text-primary d-flex justify-content-between m-2">
     <span class="d-flex align-items-center">Number of Orders Left:</span>
     <h4 class="mt-2 mr-5">
      <span class="badge bg-danger rounded-pill text-white">
        {{ num_orders_left }}
      </span>
    </h4>
    </li>
   
  </section>
  
  <section class="mt-10 container ml-0" style="postition: relative; margin-top: 40px;">
      <div class="d-flex space-between">
        <a class="add_order" href={% url 'turbo_parser:add_order' %} >
          <button type="button" class="btn btn-primary">
            Add Order
          </button>
        </a>
    
      </div>
      
      <h2 style="margin-top: 20px;">Orders</h2>  

      <div class="table-responsive" style="top-margin:20px;">
        <table class="table table-striped table-sm table-hover">
          <thead>
            <tr>
              <th class="text-center" scope="col">Order id #</th>
              <th class="text-center" scope="col">Order date</th>
              <th class="text-center" scope="col">Price Threshold</th>
              <th class="text-center" scope="col">Currency</th>
              <th class="text-center" scope="col">Number of Sended Cars</th>
              <th class="text-center" scope="col">Ordered link</th>
              <th class="text-center" scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for order in my_list %}

              <tr>

                <td class="text-center"><a href={% url 'turbo_parser:order_details' order.0.id %} style="width:50px;" class="btn btn-outline-primary" >{{ order.0.id }}</a></td>
                <td class="text-center">{{ order.0.created_at }}</td>
                <td class="text-center">{{ order.0.threshold }}</td>
                <td class="text-center">{{ order.0.currency }}</td>
                <td class="text-center">{{ order.1 }}</td>
                <td class="text-center"><a href=//{{ order.0.ordered_link }} target="_blank">Link</a></td>

                <td class="text-center"><a href={% url 'turbo_parser:edit_order' order.0.id %}>Edit <i class="fas fa-pen"></i></a></td>
                <td class="text-center"><a href={% url 'turbo_parser:delete_order' order.0.id %}>Delete <i class="fas fa-trash"></i></a></td>
              </tr>
            
            {% endfor %}
            
          </tbody>
        </table>
      </div>
  </section>


</div>

  

{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/profile.html
{% extends 'turbo_parser/base.html' %}
{% load static %}

{% block custom_css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block moy_kontent %}
<div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Profile</h4>
            <form action="{% url 'turbo_parser:profile' %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{form.username.id_for_label}}">User name</label>
                        {{ form.username }}
                    </div>
                    
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{form.phone_number.id_for_label}}">Phone number</label>
                            {{ form.phone_number }}
                        </div>
                    </div>
                </div>
                <div class="form-row">

                    <div class="col-lg-4">
                        <label class="small mb-1" for="{{form.max_num_of_orders.id_for_label}}">Maximum number of orders</label>
                        {{ form.max_num_of_orders }}
                    </div>
                    <div class="col-lg-4">
                        <label class="small mb-1" for="inputActiveNumOrders">Active number of orders</label>
                        <input class="form-control py-4" id="inputActiveNumOrders" type="number"
                               value="{{ user_orders }}" disabled/>
                        
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-10">
                        {% include 'turbo_parser/telegram_bot.html' %}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Save">
                    </div>
                </div>

            </form>
        </div>
        
    </div>
</div>
{% endblock moy_kontent %}

turbo_parser/templates/turbo_parser/telegram_bot.html
<div class="col-lg-8">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Telegram bot: (@Joonny_Bot) <span class="badge badge-success badge-pill">Active</span>
    </h4>

    <div class="card mb-3">
        <div class="card-footer">
            <h5 class="float-left">Telegram chat id: </h5>
            {{form.telegram_chat_id}}
        </div>
        <button type="button" id="btn" onclick="myFun()" class="btn btn-success btn-lg float-right">Change</button>
    </div>
</div>

<script>
    tel_chat_id = document.getElementById("telegram_chat_id");
    btn = document.getElementById("btn");

    function myFun() {

        if (tel_chat_id.readOnly) {
            
            tel_chat_id.readOnly = false;
            btn.innerText = "Done";
        } else if (tel_chat_id.value=='') {
            tel_chat_id.readOnly = true;
            btn.innerText = "Add";
        } else {
            tel_chat_id.readOnly = true;
            btn.innerText = "Change";
        }

        
    }
    window.onload = function(){
        if (tel_chat_id.getAttribute("value")==null) {
            btn.innerText = "Add";
        } else {
            btn.innerText = "Change";
        }
    }
</script>